name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push genetics
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/genetics/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/genetics:latest
      -
        name: Build and push ldsc
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/ldsc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ldsc:latest
          
